@baseUrl = http://localhost:3333/api/v1
@authtoken = {{auth_partner_with_password.response.body.token}}

# @name create_partner
POST {{baseUrl}}/partners
Content-Type: application/json

{
  "name": "Alvaro",
  "email": "alvaro@email.com",
  "password": "123456"
}

###

# @name send_partner_confirmation
POST {{baseUrl}}/partners/send-confirmation
Content-Type: application/json

{
  "email": "alvaro@email.com"
}

###

# @name confirm_partner
POST {{baseUrl}}/partners/email-confirmation
Content-Type: application/json

{
  "email": "alvaro@email.com"
}

###

# @name get_partner
GET {{baseUrl}}/partners/15d41b4b-a0bd-4235-aef9-a55f5612ab68
Content-Type: application/json

###

# @name get_all_partners
GET {{baseUrl}}/partners
Content-Type: application/json
Authorization: Bearer {{authtoken}}

###

# @name auth_partner_with_password
POST {{baseUrl}}/partners/sessions
Content-Type: application/json

{
  "email": "alvaro@email.com",
  "password": "123456"
}

###

# @name create_merchant
POST {{baseUrl}}/merchants
Content-Type: application/json
Authorization: Bearer {{authtoken}}

{
  "name": "Buzz Pizza",
  "description": "As melhores pizzas da região",
  "cnpj": "00000000000100"
}